#!/usr/bin/env python3
"""Run the county-wide WCR extraction in spiral order (tools/spiral_plan.json), resumable, with verify-then-push batches.

  nohup /workspace/.venv-pw/bin/python tools/spiral_run.py --push >> .cache/spiral.log 2>&1 &
  /workspace/.venv-pw/bin/python tools/spiral_run.py --status          # print progress / ETA, rewrite tools/spiral_plan.md
  options: --rings 1,2  --areas julian,alpine  --batch 150 (permits per commit)  --delay 2.5  --no-push-live-check

Per batch (default 150 permits, ~35 min at ~14 s/permit):
  extract_county_wcr.py --permits <batch> --area <id>  ->  headless phone check (tools/verify_wcr_area.py) of a sample of
  the new permits  ->  git commit + push  ->  wait until the live GitHub Pages manifest/tiles have the new permits and re-check a
  sample on the live site.  If the local check fails, nothing is pushed from then on (extraction continues; see log).
Resume: just start it again. Permits already in data/county-wcr/ are skipped; progress is derived from the cache files.
Polite: extract_county_wcr.py makes one county request at a time with --delay between; if a batch is mostly errors
(county servers down / throttling) the runner backs off 15 min and retries, and stops after 3 bad batches in a row.
Stop: kill <pid> (SIGTERM; the current permit may be lost and is redone on resume). Lock: .cache/spiral.lock
"""
import argparse, collections, datetime as dt, fcntl, json, os, random, subprocess, sys, time, urllib.request
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_county_wcr import tile_key  # noqa: E402  (same grid as the shards)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = '/workspace/.venv-pw/bin/python'
PLAN = os.path.join(ROOT, 'tools', 'spiral_plan.json')
PROG = os.path.join(ROOT, 'tools', 'spiral_progress.json')
MD = os.path.join(ROOT, 'tools', 'spiral_plan.md')
OUT = os.path.join(ROOT, 'data', 'county-wcr')
LIVE = 'https://aspinwelldrilling-commits.github.io/wells-nearby/'
GIT_ENV = dict(os.environ, GIT_AUTHOR_NAME='aspinwelldrilling-commits', GIT_COMMITTER_NAME='aspinwelldrilling-commits',
               GIT_AUTHOR_EMAIL='aspinwelldrilling-commits@users.noreply.github.com',
               GIT_COMMITTER_EMAIL='aspinwelldrilling-commits@users.noreply.github.com')
SEC_PER_PERMIT = 14.5  # measured on Ramona / Valley Center (delay 2.5 s)
RED = ('unreadable', 'partial', 'no_wcr')


def log(*a):
    print(time.strftime('%Y-%m-%d %H:%M:%S'), *a, flush=True)


def load_json(p, default):
    try: return json.load(open(p))
    except Exception: return default


def status_of(permit):
    r = load_json(os.path.join(OUT, permit + '.json'), None)
    return r.get('status') if r else None


def area_counts(a):
    c = collections.Counter(status_of(p) or 'todo' for p in a['permits'])
    return dict(c)


def write_md(plan, prog):
    rows, tot = [], collections.Counter()
    for a in plan['areas']:
        c = area_counts(a); tot.update(c); pr = prog['areas'].get(a['id'], {})
        done = a['count'] - c.get('todo', 0)
        st = 'done' if done == a['count'] else ('in progress' if done else 'pending')
        live = pr.get('liveCount', 0)
        rows.append(f"| {a['order']} | {a['ring']} | {a['name']} (`{a['id']}`) | {a['distMi']} | {a['count']} | {done} | {c.get('readable', 0)} | "
                    f"{c.get('partial', 0)} | {c.get('unreadable', 0)} | {c.get('no_wcr', 0)} | {c.get('no_docs', 0) + c.get('error', 0) + c.get('destruction_wcr', 0)} | "
                    f"{st} | {live if live else '—'} |")
    todo = tot.get('todo', 0); hrs = todo * SEC_PER_PERMIT / 3600
    md = f"""# County WCR extraction — spiral plan & progress

Generated by `tools/spiral_run.py` ({dt.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M %Z')}). Plan: `tools/spiral_plan.json`
(built by `tools/build_spiral_plan.py`: every non-destruction county DEH well permit — {plan['totalPermits']} — is assigned to the
nearest named area center; rings spiral outward from Ramona; within a ring, nearest first).

Remaining: **{todo} permits ≈ {hrs:.0f} h** at ~{SEC_PER_PERMIT:.0f} s/permit (one county request at a time, 2.5 s apart).

Run / resume (background, verify-then-push every 150 permits):

    cd /workspace/wells-app && nohup /workspace/.venv-pw/bin/python tools/spiral_run.py --push >> .cache/spiral.log 2>&1 &
    /workspace/.venv-pw/bin/python tools/spiral_run.py --status     # progress + ETA

"Live" = permits of the area confirmed in the live GitHub Pages shards (manifest hash + tile contents) after the last verified push.
"other" = no_docs + error + destruction report.

| # | Ring | Area | mi from Ramona | Permits | Processed | Readable | Partial | Unreadable | No WCR | Other | Status | Live |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
""" + '\n'.join(rows) + f"""
| | | **Total** | | {plan['totalPermits']} | {plan['totalPermits'] - todo} | {tot.get('readable', 0)} | {tot.get('partial', 0)} | {tot.get('unreadable', 0)} | {tot.get('no_wcr', 0)} | {tot.get('no_docs', 0) + tot.get('error', 0) + tot.get('destruction_wcr', 0)} | | |
"""
    open(MD, 'w').write(md)
    return todo, hrs


def save_prog(prog):
    json.dump(prog, open(PROG, 'w'), indent=1)


def git(*args, check=True):
    r = subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True, env=GIT_ENV)
    if check and r.returncode: raise RuntimeError(f'git {" ".join(args)}: {r.stderr.strip()[:300]}')
    return r.stdout.strip()


def sample(permits, k_read=4, k_red=5):
    by = collections.defaultdict(list)
    for p in permits: by[status_of(p)].append(p)
    random.shuffle(by['readable'])
    red = by['unreadable'] + by['partial'] + by['no_wcr']; random.shuffle(red)
    return by['readable'][:k_read] + red[:k_red]


def verify(permits, base=''):
    if not permits: return True, 'nothing to verify'
    cmd = [PY, os.path.join(ROOT, 'tools', 'verify_wcr_area.py'), ','.join(permits)] + (['--base', base] if base else [])
    for attempt in (1, 2):
        r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=1800)
        out = (r.stdout + r.stderr).strip()
        for line in out.splitlines(): log('   verify:', line)
        if r.returncode == 0: return True, out.splitlines()[-1] if out else ''
        time.sleep(60)
    return False, out[-500:]


def wait_live(permits, timeout=1200):
    """True once the live manifest lists, for every tile holding one of these permits, the same content hash as the local
    manifest, and the live tiles actually contain the permits."""
    man = load_json(os.path.join(OUT, 'manifest.json'), {}).get('tiles', {})
    keys = {}
    for p in permits:
        r = load_json(os.path.join(OUT, p + '.json'), {})
        if r.get('lat') is not None: keys.setdefault(tile_key(r['lat'], r['lon']), []).append(p)
    t0 = time.time()
    while time.time() - t0 < timeout:
        try:
            get = lambda u: json.load(urllib.request.urlopen(urllib.request.Request(LIVE + u, headers={'Cache-Control': 'no-cache'}), timeout=60))
            live = get(f'data/county-wcr/manifest.json?ts={int(time.time())}').get('tiles', {})
            stale = [k for k in keys if (live.get(k) or {}).get('h') != (man.get(k) or {}).get('h')]
            if not stale:
                missing = [p for k, ps in keys.items() for p in ps if p not in get(f'data/county-wcr/tiles/{k}.json?v={man[k]["h"]}').get('permits', {})]
                if not missing: return True, sum(t['n'] for t in live.values())
                log('   live tiles missing permits:', missing[:5])
        except Exception as e:
            log('   live check error', str(e)[:120])
        time.sleep(45)
    return False, 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rings', default=''); ap.add_argument('--areas', default=''); ap.add_argument('--batch', type=int, default=150)
    ap.add_argument('--delay', type=float, default=2.5); ap.add_argument('--push', action='store_true')
    ap.add_argument('--no-push-live-check', action='store_true'); ap.add_argument('--status', action='store_true')
    a = ap.parse_args()
    plan = load_json(PLAN, None); prog = load_json(PROG, {'areas': {}})
    if a.status:
        todo, hrs = write_md(plan, prog)
        for ar in plan['areas']:
            c = area_counts(ar); print(f"{ar['order']:>2} r{ar['ring']} {ar['id']:<20} {ar['count'] - c.get('todo', 0):>5}/{ar['count']:<5} {c}")
        print(f'remaining {todo} permits ≈ {hrs:.1f} h'); return
    lock = open(os.path.join(ROOT, '.cache', 'spiral.lock'), 'w')
    try: fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError: log('another spiral_run is already running (.cache/spiral.lock) — exiting'); sys.exit(1)
    lock.write(str(os.getpid())); lock.flush()
    rings = {int(x) for x in a.rings.split(',') if x.strip()}; only = {x.strip() for x in a.areas.split(',') if x.strip()}
    areas = [ar for ar in plan['areas'] if (not rings or ar['ring'] in rings) and (not only or ar['id'] in only)]
    push_ok = a.push; bad_streak = 0
    log(f'spiral run pid {os.getpid()}: {len(areas)} areas, push={a.push}, batch={a.batch}, delay={a.delay}')
    for ar in areas:
        pr = prog['areas'].setdefault(ar['id'], {'batches': []})
        retried_errors = False
        while True:
            todo = [p for p in ar['permits'] if status_of(p) is None]
            if not todo and not retried_errors:
                errs = [p for p in ar['permits'] if status_of(p) == 'error']
                retried_errors = True
                if errs:
                    log(f"{ar['id']}: retrying {len(errs)} errored permits once")
                    for p in errs: os.remove(os.path.join(OUT, p + '.json'))
                    continue
            if not todo:
                log(f"{ar['id']}: complete {area_counts(ar)}"); break
            batch = todo[:a.batch]
            log(f"{ar['id']} (ring {ar['ring']}): {len(todo)} to do, batch of {len(batch)}")
            t0 = time.time()
            r = subprocess.run([PY, os.path.join(ROOT, 'tools', 'extract_county_wcr.py'), '--permits', ','.join(batch), '--area', ar['id'], '--delay', str(a.delay)],
                               cwd=ROOT, capture_output=True, text=True)
            for line in (r.stdout + r.stderr).strip().splitlines()[-3:]: log('   extract:', line)
            done = [p for p in batch if status_of(p)]
            c = collections.Counter(status_of(p) for p in done)
            secs = (time.time() - t0) / max(1, len(done))
            log(f"   batch done: {len(done)}/{len(batch)} {dict(c)} {secs:.1f} s/permit")
            if r.returncode != 0 and not done:
                log('   extractor failed with nothing done — stopping'); sys.exit(2)
            if c.get('error', 0) > 0.5 * max(1, len(done)):
                bad_streak += 1
                log(f'   mostly errors (county servers?) — backing off 15 min (streak {bad_streak})')
                for p in done:
                    if status_of(p) == 'error': os.remove(os.path.join(OUT, p + '.json'))
                subprocess.run([PY, os.path.join(ROOT, 'tools', 'extract_county_wcr.py'), '--reparse'], cwd=ROOT, capture_output=True)  # rebuild index
                if bad_streak >= 3: log('   3 bad batches in a row — stopping; resume later'); sys.exit(3)
                time.sleep(900); continue
            bad_streak = 0
            entry = {'at': dt.datetime.now().astimezone().isoformat(timespec='seconds'), 'n': len(done), 'counts': dict(c), 'secPerPermit': round(secs, 1)}
            write_md(plan, prog)
            if push_ok:
                s = sample(done)
                ok, msg = verify(s)
                entry['verified'] = ok
                if not ok:
                    log('   LOCAL VERIFICATION FAILED — pushing disabled for the rest of this run:', msg)
                    push_ok = False
                else:
                    total = len(ar['permits']) - area_counts(ar).get('todo', 0)
                    save_prog(prog); write_md(plan, prog)
                    git('add', 'data/county-wcr', 'tools/spiral_progress.json', 'tools/spiral_plan.md')
                    git('commit', '-q', '-m', f"WCR cache: {ar['name']} (+{len(done)}, {total}/{ar['count']}) {dict(c)}")
                    try:
                        git('pull', '-q', '--rebase'); git('push', '-q')
                        entry['commit'] = git('rev-parse', '--short', 'HEAD'); log('   pushed', entry['commit'])
                        if not a.no_push_live_check:
                            live, n = wait_live(done)
                            entry['live'] = live
                            if live:
                                pr['liveCount'] = total
                                okl, msgl = verify(s[:3], LIVE)
                                entry['liveVerified'] = okl
                                log(f'   live: shards have {n} permits; live app check: {"ok" if okl else "FAILED " + msgl[-200:]}')
                            else:
                                log('   live site did not show the new permits within 20 min')
                    except Exception as e:
                        log('   push failed:', str(e)[:300]); push_ok = False
            pr['batches'].append(entry); save_prog(prog); write_md(plan, prog)
            if push_ok and entry.get('commit'):
                # commit the tracker update (live status) with the next batch; keep the tree clean otherwise
                pass
    todo, hrs = write_md(plan, prog); save_prog(prog)
    log(f'run finished; remaining {todo} permits (~{hrs:.1f} h)')


if __name__ == '__main__':
    main()
